// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5787ZIXJbm0TJ-rNdb6wjKOx2eNSLXgc',
    appId: '1:878387900440:web:a0c7332cb01c56339a936d',
    messagingSenderId: '878387900440',
    projectId: 'bookstore-66d27',
    authDomain: 'bookstore-66d27.firebaseapp.com',
    storageBucket: 'bookstore-66d27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJrVi1LCRdjE6HTD8xcGERiCgRavzRlw',
    appId: '1:878387900440:android:b89703168b917a0b9a936d',
    messagingSenderId: '878387900440',
    projectId: 'bookstore-66d27',
    storageBucket: 'bookstore-66d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwb3IrflK5MVnG316t6OfdgzGz11wCuMw',
    appId: '1:878387900440:ios:5e936c5f829163179a936d',
    messagingSenderId: '878387900440',
    projectId: 'bookstore-66d27',
    storageBucket: 'bookstore-66d27.appspot.com',
    androidClientId: '878387900440-5lr69hctorkuphr4dv4105vt4nmhagsj.apps.googleusercontent.com',
    iosClientId: '878387900440-6cm1hlt6567sm267qs983nvgk3u2s8m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
